title: SWAN Package Manager
description: Jupyter extension for managing conda packages
owner: Akash Ravi

theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/techtocore/Jupyter-Package-Manager